spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carpet_db
    username: glebramazanov
    password:
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  jackson:
    # Сериализация и десериализация JSON в snake_case
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

# Swagger UI — http://localhost:8080/swagger-ui.html
# OpenAPI спецификация — http://localhost:8080/v3/api-docs
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

server:
  port: 8080
